### ISSUE TITLE
Your `isEmail` is broken

### ISSUE THREAD

**Issue by RandalSchwartz** [Aniketkhote/Quickly#1]
```
bool get isEmail => regex(
      r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+");
```
No, please don't use this regex to validate email.  It's wrong.  The shortest regex to validate an RFC822 email address is about 2400 characters, and is given in https://www.ex-parrot.com/pdw/Mail-RFC822-Address.html.  Anything shorter is WRONG, unless you're using a grammar, as package:email_validator properly does.  Use that for Dart/Flutter please.

**Comment by Aniketkhote** [comment]
Thank you for bringing this to our attention. I completely agree that using a proper library such as package:email_validator is the recommended approach to validate email addresses in Dart/Flutter. Relying on a regex can lead to incorrect results and should be avoided. I'll make sure to update the code accordingly. Thank you for pointing this out!
