### ISSUE TITLE
migrate from getx to refreshed

### ISSUE THREAD

**Issue by victorlunam** [Aniketkhote/Quickly#3]
The idea of [removing](https://github.com/Aniketkhote/refreshed/blob/1d038a52b8197199b809ed3c4527947079ed8bca/CHANGELOG.md?plain=1#L100-L103) some helpers from `get_utils` was to replace it with `Quickly`.

I create this issue to report the helpers that are not yet in `Quickly` that are widely used in `getX`.

**Comment by victorlunam** [comment]
* https://github.com/Aniketkhote/refreshed/issues/36

**Comment by aniketkhote9** [comment]
Updated to the latest version with additional string extensions. Let me know if there's anything specific you'd like to see added!
